version: '3.1'

services:
  nightfoxcontainer:
    image: nightfoxreview:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - mongodb
      - mongo-express
    networks:
      - nightfoxreviewnetwork
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - nightfoxreviewnetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
#    depends_on:
#      - "mongodb"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - nightfoxreviewnetwork
volumes:
    mongo-data:
networks:
    nightfoxreviewnetwork:
      driver: bridge